### ISSUE TITLE
Deluge for UCmote Mini

### ISSUE THREAD

**Issue by cgomezca** [tinyos/tinyos-main#327] opened 2015-02-18 14:50 UTC
Hi all.

I'm involved in a project where the hardware chosen is UCmote Mini. We require to use Deluge on them, but unfortunately Deluge is not offered for UCmote mini yet. Could any of you tell me a starting point? Any help would be appreciated.

Thanks in advance.

**Comment by andrasbiro** [comment] 2015-02-26 15:01
Hi,

I have a kind-of-working solution here:
https://github.com/szte-wsn/tinyos-main/commits/deluge

Last time I checked I could use it to program the motes once, but couldn't reprogram them. After that, I didn't need it, so it remained in this "I should check this when I have time" state.
Merging it to tinyos-main would be complicated, because deluge/tosboot has some dead code and some code duplication, and I tried to get rid of it, but again, it should be checeked again before merging.

Keep in mind that you'll need a JTAG programmer for the ucmini to replace the avr109 copatible bootloader with tosboot.

I replied here, because I think this information should be public, but I'm also closing this, since it's not a bug.

**Closed by andrasbiro** 2015-02-26 15:01 UTC
